# Prototype Pipeline - React

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Use Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build React app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'react-app'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'react-app'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
