## Author: Ali Bonagdaran

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '20.x'
  HUSKY: '0'
  CI: 'true'
  NODE_OPTIONS: '--max-old-space-size=4096'  # Increase Node.js memory limit
  
stages:
  - stage: CI
    displayName: 'Continuous Integration'
    jobs:
      - job: Lint
        displayName: 'Lint Code'
        steps:
          - template: .azure/templates/setup-node.yml
          - script: npm run lint:ci || true
            displayName: 'Run ESLint with caching'
            env:
              NEXT_TELEMETRY_DISABLED: 1

      - job: UnitTests
        displayName: 'Unit Tests'
        steps:
          - template: .azure/templates/setup-node.yml
          - script: npm run test:coverage
            displayName: 'Run Unit Tests with Coverage'
            env:
              CI: true
              NEXT_TELEMETRY_DISABLED: 1
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'test-results/**/*.xml'
          - task: PublishCodeCoverageResults@2
            condition: succeededOrFailed()
            inputs:
              summaryFileLocation: 'coverage/cobertura-coverage.xml'
              pathToSources: 'src/'

      # playwright tests only on main branch or when explicitly requested

      - job: E2ETests
        displayName: 'E2E Tests'
        condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['FORCE_E2E'], 'true'))
        steps:
          - template: .azure/templates/setup-node.yml
          - script: npx playwright install --with-deps chromium
            displayName: 'Install Playwright browsers'
          - script: npm run test:e2e:ci
            displayName: 'Run E2E Tests'
            env:
              CI: true
              NEXT_TELEMETRY_DISABLED: 1
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'test-results/**/*.xml'

      - job: Build
        displayName: 'Build Application'
        dependsOn: [Lint, UnitTests]
        steps:
          - template: .azure/templates/setup-node.yml
          - task: Cache@2
            displayName: 'Cache Next.js build'
            continueOnError: true
            inputs:
              key: 'nextjs | "$(Agent.OS)" | package-lock.json | $(Build.SourceVersion)'
              path: '.next/cache'
              restoreKeys: |
                nextjs | "$(Agent.OS)" | package-lock.json
          - script: npm run build:ci
            displayName: 'Build Application'
            env:
              NEXT_TELEMETRY_DISABLED: 1
          - task: PublishPipelineArtifact@1
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              artifactName: 'WebApp'
              publishLocation: 'pipeline'
            displayName: 'Publish build artifacts'

  - stage: Deploy
    displayName: 'Deploy to Production'
    dependsOn: CI
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: Production
        displayName: 'Deploy to Azure App Service'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: WebApp
                  displayName: 'Download build artifacts'
                
                # Install dependencies and run database migrations
                - task: UseNode@1
                  inputs:
                    version: $(nodeVersion)
                  displayName: 'Use Node.js for deployment'
                
                - script: |
                    cd $(Pipeline.Workspace)/WebApp
                    npm ci --only=production
                  displayName: 'Install production dependencies'
                

                - script: |
                    cd $(Pipeline.Workspace)/WebApp
                    echo "Configuring database connection..."
                    # Use the helper script to build a properly encoded DATABASE_URL
                    DATABASE_URL=$(node scripts/build-db-url.js)
                    echo "DATABASE_URL=$DATABASE_URL" > .env
                    echo "NODE_ENV=production" >> .env
                    echo "PORT=8080" >> .env
                    echo "HOSTNAME=0.0.0.0" >> .env
                    echo "FINNHUB_API_KEY=$FINNHUB_API_KEY" >> .env
                    echo "Database configuration complete"
                    echo "Clearing existing migrations for provider switch..."
                    rm -rf prisma/migrations
                    npx prisma generate
                    echo "Syncing schema with prisma db push..."
                    npx prisma db push --skip-generate
                  displayName: 'Run database migrations'
                  env:
                    AZURE_POSTGRESQL_HOST: $(AZURE_POSTGRESQL_HOST)
                    AZURE_POSTGRESQL_USER: $(AZURE_POSTGRESQL_USER)
                    AZURE_POSTGRESQL_PASSWORD: $(AZURE_POSTGRESQL_PASSWORD)
                    AZURE_POSTGRESQL_DATABASE: $(AZURE_POSTGRESQL_DATABASE)
                    AZURE_POSTGRESQL_PORT: $(AZURE_POSTGRESQL_PORT)
                    FINNHUB_API_KEY: $(FINNHUB_API_KEY)
                
                # Build the DATABASE_URL with proper encoding
                - script: |
                    cd $(Pipeline.Workspace)/WebApp
                    DB_URL=$(node scripts/build-db-url.js)
                    echo "##vso[task.setvariable variable=ENCODED_DATABASE_URL]$DB_URL"
                  displayName: 'Build encoded DATABASE_URL'
                  env:
                    AZURE_POSTGRESQL_HOST: $(AZURE_POSTGRESQL_HOST)
                    AZURE_POSTGRESQL_USER: $(AZURE_POSTGRESQL_USER)
                    AZURE_POSTGRESQL_PASSWORD: $(AZURE_POSTGRESQL_PASSWORD)
                    AZURE_POSTGRESQL_DATABASE: $(AZURE_POSTGRESQL_DATABASE)
                    AZURE_POSTGRESQL_PORT: $(AZURE_POSTGRESQL_PORT)
                
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'OmniTrade Connection'
                    appType: 'webAppLinux'
                    appName: 'OmniTrade'
                    package: '$(Pipeline.Workspace)/WebApp'
                    runtimeStack: 'NODE|20-lts'
                    startUpCommand: 'npm start'
                    appSettings: '-NODE_ENV production -PORT 8080 -DATABASE_URL "$(ENCODED_DATABASE_URL)" -FINNHUB_API_KEY "$(FINNHUB_API_KEY)"'
                  displayName: 'Deploy to Azure App Service'