# Prototype Pipeline - React

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Use Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build React app'

- script: npm test
  displayName: 'Run Jest tests'

- task: PublishBuildArtifacts@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/bin/WebApp
    artifactName: WebApp
  displayName: 'Publish build artifacts'