# Prototype Pipeline - React

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Use Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build React app'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      .next/**
      public/**
      package.json
      package-lock.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)/WebApp'

- task: PublishBuildArtifacts@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/WebApp
    artifactName: WebApp
  displayName: 'Publish build artifacts'