# Multi-Stage React CI/CD Pipeline

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: 'Build and Publish Artifacts'
    jobs:
      - job: Build
        displayName: 'Build and Publish'
        steps:
          - task: UseNode@1
            inputs:
              version: '18.x'
            displayName: 'Use Node.js 18.x'

          - task: Cache@2
            displayName: 'Cache node_modules'
            inputs:
              key: 'npm | "$(Agent.OS)" | package.json'
              path: 'node_modules'
              cacheHitVar: 'NPM_CACHE_RESTORED'

          - script: npm install
            displayName: 'Install Dependencies'
            condition: ne(variables.NPM_CACHE_RESTORED, 'true')

          - script: npm run build
            displayName: 'Build React App'

          - task: CopyFiles@2
            displayName: 'Copy Files to Artifact Staging Directory'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: |
                .next/**
                public/**
                package.json
                next.config.mjs
              TargetFolder: '$(Build.ArtifactStagingDirectory)/WebApp'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: WebApp'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/WebApp'
              ArtifactName: 'WebApp'
          
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: node_modules'
            inputs:
              PathtoPublish: 'node_modules'
              ArtifactName: 'node_modules_for_test'

  - stage: Test
    displayName: 'Run Tests'
    dependsOn: Build
    jobs:
      - job: Test
        displayName: 'Run Unit Tests'
        steps:
          - task: UseNode@1
            inputs:
              version: '18.x'
            displayName: 'Use Node.js 18.x'

          - task: DownloadBuildArtifacts@0
            displayName: 'Download node_modules'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'node_modules_for_test'
              downloadPath: '$(System.DefaultWorkingDirectory)'

          - script: npm test
            displayName: 'Run Jest Tests'